server:
  port: 8080

gcp:
  service-account:
    key-path: ${GCP_SERVICE_ACCOUNT_KEY_PATH:classpath:ems-backend-key.json}
  vertex-ai:
    project-id: ${GCP_PROJECT_ID:158656738463}
    location: ${GCP_LOCATION:asia-northeast3}
    endpoint-id: ${GCP_ENDPOINT_ID:7393997993491300352}
    endpoint-url: https://${gcp.vertex-ai.location}-aiplatform.googleapis.com/v1/projects/${gcp.vertex-ai.project-id}/locations/${gcp.vertex-ai.location}/endpoints/${gcp.vertex-ai.endpoint-id}:predict

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ems_copilot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true  # ?? ? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}